Add Minecraft->Discord user reporting.
sciwhiz12/Concord pull request #4
Opened 2022-02-26 00:40 UTC by TheCurle

A user in-game can use the command:

```
/report <user> <reason>
```

eg. 
```
/report Curle being a nerd
```

and it will send an embed like the following to a configured channel:
![image](https://user-images.githubusercontent.com/42079760/155821101-5c697e3b-344a-45d6-88fc-8f9ba0e6cf3b.png)

The channel is in the config file, and if no channel is set, reporting is disabled.
When reports are disabled, any attempts to use the /report command will tell the player so.

Note that to clear any confusion between the report channel configuration option and the normal chat channel, i renamed the chat option.

This is a breaking change.

2022-04-30 09:09 UTC, sciwhiz12 requested changes
So, I've finally the time to review this PR. 🎉

The idea of the `report` command is solid -- allowing players to report other players from in-game to the server admins. Aside from the merge conflicts (which I will resolve myself), I have some concerns/questions about this feature.

 - Currently, only the reported user is logged to the reports channel. This poses a concern that ill-behaving users may choose to spam reports to the channel and drown out other players' reports. What reason do we have to keep the anonymity of the reporter?

 - The current design allows for the possibility of multiple reports of multiple players with a single command invocation. This conflicts with the fact that the only way to select multiple players is to use an entity selector, which is only available to operators of level 2 and above (cf. https://github.com/MinecraftForge/MinecraftForge/issues/7673). We should limit the entity argument and implementation to one player per command invocation.

 - In alignment with the two above, should we have some sort of mechanism in Concord itself to bar specific players from using the `report` command, such as a punishment handed down by server admins to players who abuse it?

 - The embed used for a report is too bland and has too little information for my tastes. I believe it should include the UUID of the player, the timestamp of the report (whether a inline one or the one built-in to the embed), and potentially the location of the player (dimension and coordinates) as well.

 - Should we expand the notion of the reports channel to be a more "administrative alerts" channel? For example, logging kicks and bans, opping and de-opping, perhaps even logging the use of admin commands in general (think the `logAdminCommands` gamerule).

 - We'll likely want to add specialized error messages for the `report` command for when reporting or the bot is disabled (perhaps the latter can be a generalized error message).

 - Should we add a configurable alias of `/report` for `/concord report`?

As an aside, I'm thinking of using the Forge permission API for controlling access to the commands, with sensible defaults based on the operator permission levels (the levels we have now).

2022-04-30 16:33 UTC, TheCurle commented
Okay, let's see:

The output embed is something i was very much uncertain of, and i voiced this concern to you via Discord.
I'm more than willing to include more information in it.

At a minimum:
* The user who reported them
* The number of times the reported user has been reported
* The UUID of the reporter and the reportee
* The position and dimension of the reporter at the time of the report
* The time of the report, in real-world and game time

I also noticed a UX issue in that no feedback is given to a player upon a sucessful report submission, this should be changed too.

I'm not aware of how it's possible to send multiple reports with a single command - there's only one entity parameter allowed, the rest is parsed as greedy text. Can you explain what you mean by "The current design allows for the possibility of multiple reports of multiple players with a single command invocation"?

As for the channel, i recommend leaving reports as a separate channel - this is something that should not be drowned out amongst things like routine warnings, kicks, etc. Purely from an administrative point of view, things that users do and things that admins do should be separated, because the former is far more important.

On that line of logic, though, a separate unified "moderation logging" channel would be a good idea.

The rest i completely agree with, and will be working on shortly.

2022-04-30 19:52 UTC, sciwhiz12 commented
> I'm not aware of how it's possible to send multiple reports with a single command - there's only one entity parameter allowed, the rest is parsed as greedy text. Can you explain what you mean by "The current design allows for the possibility of multiple reports of multiple players with a single command invocation"?

The use of `EntityArgument#players()`, `EntityArgument#getPlayers`, and a `for`-loop to send message embeds suggests the possibility of reporting multiple players with a single command, even though selectors are only available to operators (which are likely able to deal with the problematic players themselves).

Though, looking at commands like `KickCommand` seem to imply that this is the convention, so hmmm.

2022-04-30 19:57 UTC, TheCurle commented
Indeed. I use enhanced-for as a safeguard to handle the situation where the list provided is empty. It should be impossible to provide multiple players, since the greedyString will take a second name as part of itself.

2022-04-30 20:01 UTC, TheCurle commented
Marked as draft in preparation for a major refactor.

2022-04-30 20:01 UTC, TheCurle commented
I have no idea why i pressed that.

2022-04-30 20:04 UTC, sciwhiz12 commented
> Indeed. I use enhanced-for as a safeguard to handle the situation where the list provided is empty. It should be impossible to provide multiple players, since the greedyString will take a second name as part of itself.

It's not impossible, at least, because of entity selectors, but it does require operator permissions.

Also, just a small code thing I noticed: the return value of the command should be the size of the player collection (following what other commands do).

2022-04-30 22:29 UTC, TheCurle commented
As requested, i have updated the logging embed to contain more information.
![image](https://user-images.githubusercontent.com/42079760/166124642-fc77a1c1-8071-4b40-8b77-dc811c1f7341.png)

I hope to add more information to this, such as the number of times a report has been sent from the reporting user, but this is a good enough compromise for now.

2022-04-30 22:56 UTC, TheCurle commented
All feedback and requested changes have been made, except for two.

> In alignment with the two above, should we have some sort of mechanism in Concord itself to bar specific players from using the report command, such as a punishment handed down by server admins to players who abuse it?

I believe this would require more work towards the Discord-side command framework to be implemented properly, so i'll leave that for a future PR to implement.

The issue of potentially reporting multiple users has been dealt with, by only using the first found user. In normal usage this is the only user, but if the user has permission to select multiple, it will only use the first.

In my mind, this is rather unintuitive, but this is what you seemed to want, so if you'd like me to change that back, I will.

All else being said, the embed currently looks like this: 
![image](https://user-images.githubusercontent.com/42079760/166125247-cb3fba42-7fea-45c8-b015-32d22399fc14.png)


This PR is now ready for review again.

2022-05-02 23:03 UTC, sciwhiz12 approved these changes
:shipit: I'm going to pull this PR now and improve on its features through commits in the dev branch, rather than committing to the PR itself (as a maintainer with write access with the PR author's approval) and anxiously being stuck in perfectionist hell.

2022-05-02 23:04 UTC, merged